### ISSUE TITLE
.git-ftp-ignore and .git-ftp-include don't work as wished

### ISSUE THREAD

**Issue by RayanWMKI** [git-ftp/git-ftp#532] opened 2019-06-20 09:59 UTC
(git-ftp-version : 1.3.1)
(Docker image environment : Linux 426b8d13-b6d5-47a7-a859-2dac7de28c03 4.19.43-coreos #1 SMP Wed May 15 07:18:39 -00 2019 x86_64 GNU/Linux)
(local environment : Windows 10)
(process : working local, pushing the code, goes through BitBucket, then thanks to a pipeline installs git-ftp and pushes the code to FTP)

Hi !

I've been trying to make those two files work, without any real luck.
Details : 

At the first push, whatever file indicated in the .git-ftp-ignore won't be ignored.
At the second push, the files indicated will be ignored.
Then, if I decide to remove files from the .git-ftp-ignore (or even delete it), they will still be ignored.

Another issue is the trouble I have to go through to properly (find and) understand the syntax to use to ignore files.
For instance, if I want to ignore :

folderwithstuff/folderinside/* 
#here I want to only ignore this specific folder inside folderwithstuff

folderwithstuff will also be ignored.
And even if I were to include in .git-ftp-include : 

!folderwithstuff/text.txt

it will still be ignored.

Anyway, you will find the files attached to the issue, sorry if it's not clear, don't hesitate to ask other questions, have a good day !
[.git-ftp-ignore.txt](https://github.com/git-ftp/git-ftp/files/3309865/default.git-ftp-ignore.txt)
[.git-ftp-include.txt](https://github.com/git-ftp/git-ftp/files/3309866/default.git-ftp-include.txt)

**Comment by DerTanzschuh** [comment] 2019-06-20 10:54
A quick question to ensure some basic stuff: 

- Do these files have any effect at all? 
- Do they have the file extension `.txt` like your uploaded files (they shouldn’t) or is this just for uploading purposes? (Please note that Windows does not always display file extensions by default.)

**Comment by RayanWMKI** [comment] 2019-06-20 10:57
Hi !

- The git-ftp-ignore file works works after the second push, adding files to it will work, but when removing lines (or removing the file), the files ignored will remain ignored.
- It was just for uploading purposes, they are indeed by default created as .txt, but I've modified them to be .git-ftp-ignore and .git-ftp-include only.

**Comment by DerTanzschuh** [comment] 2019-06-20 13:28
Ok that’s something already. If I got you right you are trying something like this: (I tried to produce the same issue with the following test)

all files/directories in repo:
```
test.txt
ignored.txt
directory/test.txt
directory/ignoredDir/nested.txt
```
`.git-ftp-ignore`:
```
ignored.txt
directory/ignored/*
```
Do the first push, since you are using 1.3.1 there is no `auto-init` so I’ll assume you used `init`
```sh
$ git ftp init

# ! No files are ignored
```
Did I got this right?

For me it says:
```sh
Taking all files.
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
# -> this is a known issue with new git version that was fixed in 1.5.0
```

If I fix this for version 1.3.1 it says:
```sh
Thu Jun 20 15:12:29 CEST 2019: Having files to sync.
Thu Jun 20 15:12:29 CEST 2019: 3 files to sync:
Thu Jun 20 15:12:29 CEST 2019: [1 of 3] Buffered for upload '.git-ftp-ignore'.
Thu Jun 20 15:12:29 CEST 2019: [2 of 3] Buffered for upload 'directory/test.txt'.
Thu Jun 20 15:12:29 CEST 2019: [3 of 3] Buffered for upload 'test.txt'.
Thu Jun 20 15:12:29 CEST 2019: Uploading ...
```
So in short, for me it’s working as it should. I’cant reproduce the issue on my local machine :/

---

But how could you try to fix this?
Can you try to install a newer version of Git-ftp in your pipeline? The changelog lists some changes in connection with .git-ftp-ignore for version 1.5.. The [installation instructions for Debian and Ubuntu](https://github.com/git-ftp/git-ftp/blob/master/INSTALL.md#debian-ubuntu-and-others-using-apt) might help.

If this doesn’t work feel free to post here and we can try to find an other solution.

**Comment by RayanWMKI** [comment] 2019-06-20 15:24
Ok so after going a (way too long) process to get the appropriate docker image for my server (was using samueldebruyn/debian-git, switched to dotsunited/git-ftp), and get the latest version of git-ftp (now 1.5.2), my .git-ftp-ignore seems to work now ! 

My other concern was about the syntax to use for those files, I feel quite lost on how to scope for a specific file/directory since (taking your example) :

**directory**/**ignored**/*

makes the folder **directory** and the files it contains ignored, instead of just ignoring the folder **ignored**.

I hope I'm clear, thanks for your time !

**Comment by DerTanzschuh** [comment] 2019-06-20 16:03
Great you found a solution. Thanks for posting it here, the information about the docker images might help others too.

---
> `directory/ignored/*` makes the folder directory and the files it contains ignored, instead of just ignoring the folder ignored.

That’s not completely true. As you can see in my example the file `directory/test.txt` **is** not ignored and uploaded to the server, but the file `directory/ignoredDir/nested.txt` is not synced. 

**Maybe the files** you have in your `folderwithstuff` **are ignored because of the other rules** in your ignore file. For example `*.txt` matches all txt files, not only the ones in root. And if there is no file in the directory to sync it is not created.

**Comment by RayanWMKI** [comment] 2019-06-21 07:54
No problem, updated them to give as much as information as possible.

" Maybe the files you have in your folderwithstuff are ignored because of the other rules in your ignore file. For example *.txt matches all txt files, not only the ones in root. And if there is no file in the directory to sync it is not created. "

Ohhhhh that's why ! 
I think I should be good now, thank you very much for your time and help !!
Have a very good day ! 😄 

(If anyone has a problem like that, don't hesitate to PM me, I'll be glad to help with the little I got to experience)

**Comment by DerTanzschuh** [comment] 2019-06-21 08:51
You’re welcome. Glad I was able to help. 

I will close this issue for now but please feel free to re-open it or create a new one if you still have this or another problem with Git-ftp.

**Closed by DerTanzschuh** 2019-06-21 08:51 UTC
