### ISSUE TITLE
Why all my uploaded directory name are prefixed with hash-sign(#) automatically

### ISSUE THREAD

**Issue by hungdoan2** [git-ftp/git-ftp#258] opened 2016-05-09 07:03 UTC
See bellow screenshot: 
**My origin directory structure:**

> /releases/
> /releases/test.txt
> /releases/test-dir/test.txt

> /public-content/
> /public-content/test.txt
> /public-content/test-dir/test.txt

**When upload to ftp server**
`git ftp init`

**Then output is:**

> /#releases/
> /#releases/test.txt
> /#releases/test-dir/test.txt

> /#public-content/
> /#public-content/test.txt
> /#public-content/test-dir/test.txt
![screenshot_1](https://cloud.githubusercontent.com/assets/11371581/15105688/e90386e2-15ed-11e6-8548-b01a11fd598f.png)

*More info:*
`Client`: msysgit, Windows 10
`Server`: FTP Server - IIS 8.5, Windows Server 2012

**Comment by mkllnk** [comment] 2016-05-09 08:32
This is a bug in MINGW32. A newer version fixes the problem.

Duplicate of #256.

**Comment by hungdoan2** [comment] 2016-05-09 09:10
Thank you very much, you are my guardian angel today :+1: 

Ah, one more question!
My `.git-ftp-ignore`  looks not working

`.git-ftp-ignore` content: 

````
.git
.git/*
.gitignore
.git-ftp-ignore
README.MD
````
But It stills push .gitignore,.git-ftp-ignore, README.MD to FTP server

**Comment by mkllnk** [comment] 2016-05-09 12:01
Can you give me the output of `git ls-files README.MD`? I'm wondering if it could be a mismatch of lower and upper case letters since Windows doesn't really care about that.

**Comment by mkllnk** [comment] 2016-05-09 12:04
Another thing to test would be windows newlines. You could try this in your git console:
```sh
echo .gitignore > .git-ftp-ignore
echo .git-ftp-ignore >> .git-ftp-ignore
echo README.MD >> .git-ftp-ignore
```

**Comment by hungdoan2** [comment] 2016-05-09 13:10
@mkllnk  thanks you, I don't really know what's happening . But It's working without any change :)

**Closed** 2016-05-09 13:10 UTC
