### ISSUE TITLE
error: pathspec '' did not match any file(s) known to git.

### ISSUE THREAD

**Issue by mploigt** [git-ftp/git-ftp#263] opened 2016-05-23 11:20 UTC
When I'm doing a `git ftp push` I'll get the above mentioned error message, but after that everything works as expected. Do you have any idea what might trigger this message?

**Comment by stephan-v** [comment] 2016-05-26 12:48
Getting the exact same, hopefully somebody can help out here.

**Comment by mkllnk** [comment] 2016-05-26 13:08
I think it's nothing to worry about. Git introduced that warning on empty path specs at some point. It happens when $syncroot is empty. I will work on a patch to avoid that error message.

**Comment by mkllnk** [comment] 2016-06-08 12:59
Sorry, I can't reproduce this. Which Git version do you use? And which operating system?

**Comment by mploigt** [comment] 2016-06-08 14:38
I have set up a new system and now I don't get this error any more. I'm currently using git version 2.8.3 on a Mac (El Captain 10.11.5).

**Comment by LukasFritzeDev** [comment] 2019-06-24 17:47
According to #380 the behaviour of git was changed since git version 2.11.0. And this issue was fixed with Git-ftp in #380 and version 1.5.0

Therefore I will close this issue but please feel free to re-open it if you still have this problem with Git-ftp.

**Closed by LukasFritzeDev** 2019-06-24 17:47 UTC
