### ISSUE TITLE
Check if remote is inited already

### ISSUE THREAD

**Issue by ralphbolliger** [git-ftp/git-ftp#302] opened 2016-11-25 15:56 UTC
I'm wondering if there's a possibility to check first if the remote repo is inited already. If it's inited then `push` else `init`.

**Comment by mkllnk** [comment] 2016-11-27 06:22
Currently not, but it would be good. A few people requested that already.

**Comment by miguelxt** [comment] 2016-12-06 04:13
+1

**Comment by luismiguelprs** [comment] 2017-02-16 13:47
+1

**Comment by rastographics** [comment] 2017-02-17 21:31
This is needed for bitbucket Pipelines deploy feature. If deploying for first time, there is an error if I use `init`. If I try to use `push` then it works, except for the first time.

**Comment by ralphbolliger** [comment] 2017-02-18 14:40
@rastographics that's strange. Normally everything goes fine if you run your pipeline for the first time with `init`. Then you have to change the bitbucket-pipeline.yml and change the command from `init` to `push`. You have to do this on every feature branch you deploy with pipelines.

**Comment by rastographics** [comment] 2017-02-19 00:49
Sorry in my explanation I just reversed the 2 commands.  The point i was trying to make is that if we could add a flag to the push command like  --init-if-not-exist then we could run the pipeline without needing to remember if we already ran one,  then going and updating the file. 

Thank you for this tool by the way.  Very useful to me

**Comment by mkllnk** [comment] 2017-02-19 07:49
@rastographics If you are confident that you are deploying the right thing, than you can use the `force` option to push anyway.

**Comment by ralphbolliger** [comment] 2017-02-19 08:54
@mkllnk If I'm not mistaken `force` will only work if the remote repo is inited (`init`) already. so `git-ftp init --init-if-not-exist` would be the desired solution.

**Comment by mkllnk** [comment] 2017-02-23 07:07
You are right. That changed at some point.

**Comment by mkllnk** [comment] 2017-02-23 07:27
This is a duplicate of #290 and could be solved by #331.

**Comment by Arood** [comment] 2017-04-24 09:04
So the pull request seems to be merged, so I guess this is solved now?

I have a follow up question though, can anyone make an updated example of using bitbucket pipelines with this? Last time I checked it seemed like the `samueldebruyn/debian-git` image had a pretty old version of git-ftp.

**Comment by mkllnk** [comment] 2017-04-24 10:21
Thanks for mentioning that. I will close this issue.

To your other question. In a disposable container, you can install the newest version of Git-ftp in two lines:
```sh
sudo curl https://raw.githubusercontent.com/git-ftp/git-ftp/master/git-ftp -o /bin/git-ftp
sudo chmod +x /bin/git-ftp
```

On your own machine, I would recommend a packaged version, e.g. a deb file from https://launchpad.net/~git-ftp/+archive/ubuntu/ppa.

**Closed by mkllnk** 2017-04-24 10:21 UTC
Labels: duplicate, enhancement
