### ISSUE TITLE
generating a git-tmp file

### ISSUE THREAD

**Issue by stefan694** [git-ftp/git-ftp#191] opened 2015-04-27 14:07 UTC
Hi, 

Since yesterday i am getting a git-ftp-tmp as an untracked file in git and it is stopping me from pushing to theserver. I tried committing the file (which is empty BTW) and I get an error that it can't open this file.
I can't deploy anymore with git ftp.

Have any of you ever encountered this problem ?

**Comment by mkllnk** [comment] 2015-04-30 08:34
Hi Stefan,

Which version of git-ftp are you using?

The newest version tries to create the directory `.git/git-ftp-tmp` if the command `mktemp` is missing. That happens with Git For Windows. But I don't know why it would appear in your working tree and why it is a file.

Can you give more information on your operating system? In which environment do you use `git-ftp`?

**Comment by stefan694** [comment] 2015-04-30 08:39
I'm on OSX yosemite and version 1.0.2 of git ftp, the project is a wordpress website. I managed to deploy my files  putting the tmp file file in my .gitignore but I hope it won't cause any future problems.

**Comment by mkllnk** [comment] 2015-04-30 08:59
Ok, I assume you have `mktemp` installed. Can you check this command?

    command -v mktemp

And thanks for your solution of the problem. Can you delete the file?

    rm git-ftp-tmp

That should be no problem. Or does it re-appear when using `git-ftp`? What are the file permissions?

    ls -la git-ftp-tmp
Thanks for the quick reply.

**Comment by knilob** [comment] 2015-06-10 22:06
I also saw this today on my Mac (OS X Yosemite 10.10.3). I too have version 1.0.2 of git-ftp, and my file was named ".git-ftp-tmp". It was deleted after I made another change and pushed to the server. Still not sure why it appeared in the first place. I do have mktemp installed, but I didn't check the permissions since it was already deleted before I found this thread.

**Comment by aheissenberger** [comment] 2015-07-08 07:36
I do have the same problem with "git-ftp version 1.0.1" on OSX 10.10.4 after every call of "git ftp push --scope" on branch master.

I only see this file '.git-ftp-tmp' with my git client but not in the file system:
```bash
$ find . -name '*ftp*'
./.git-ftp-ignore
```

```bash
rm .git-ftp-tmp
rm: .git-ftp-tmp: No such file or directory
```

```bash
git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    .git-ftp-tmp

no changes added to commit (use "git add" and/or "git commit -a")
```

I think that somewhere in the past, the file `.git-ftp-tmp` was committed.

**I fixed it by committing the delete and add it to `.gitignore`**

**Comment by karol-haltenberger** [comment] 2015-11-24 13:09
This happened to me after pushing when there were no changes.
I'm not sure if this was the only time the file got created, but I seem to be able to reproduce it this way.

* complete a successful git ftp push (I suppose init would work too)
* issue a git ftp push again, without changing the workspace

Ubuntu 14.04
git ftp 1.0.2

    $ command -v mktemp
    /bin/mktemp

Yes I can remove the temp file

**Comment by mkllnk** [comment] 2015-11-29 09:17
Thanks @karol-haltenberger. I could reproduce that behaviour in version 1.0.2, but not in version 1.1.0. I recommend updating. Does anyone need a backport of the fix to the 1.0.x branch?

**Closed by mkllnk** 2015-11-29 09:17 UTC
Labels: confirmed

**Comment by internetvandingen** [comment] 2019-05-29 19:22
Hi, I ran into this bug on ubuntu 16.04 because I installed git-ftp with apt-get install.
1.0.2-1 is the most recent version, is it possible that this can be updated?

**Comment by DerTanzschuh** [comment] 2019-05-29 19:42
@internetvandingen maybe you can have a look at #410
