### ISSUE TITLE
.git-ftp-include doesn't do anything

### ISSUE THREAD

**Issue by danieldiekmeier** [git-ftp/git-ftp#205] opened 2015-07-20 11:20 UTC
I try to upload a folder with generated things that is in my `.gitignore`. I tried with `1.0.2` and with `1.1.0-UNRELEASED` (current develop snapshot), and although they output different things, neither one works.

My .git-ftp-include:

```
!wordpress/wp-content/themes/vgdw15/static/
```

My .gitignore:

```
node_modules
/wordpress/wp-content/themes/vgdw15/static
/wordpress/wp-config.php
.git-ftp-tmp
```

Output for `git ftp init -D` with 1.1.0 (shortened):

```
[...]
[737 of 1305] Buffered for upload 'wordpress/wp-content/themes/vgdw15/parts/person.php'.
[738 of 1305] Buffered for upload 'wordpress/wp-content/themes/vgdw15/single.php'.
[739 of 1305] Buffered for upload 'wordpress/wp-content/themes/vgdw15/style.css'.
[740 of 1305] Buffered for upload 'wordpress/wp-cron.php'.
[...]
[1305 of 1305] Buffered for upload 'wordpress/xmlrpc.php'.
Last deployment changed to 860e1402c16c004b024b457824e4b38d0c932295.
```

Output for `git ftp init -D` with 1.0.2 (shortened):

```
[...]
[1304 of 1305] Buffered for upload 'wordpress/xmlrpc.php'.
[1305 of 1305] Buffered for upload 'wordpress/wp-content/themes/vgdw15/static/'.
Last deployment changed to 860e1402c16c004b024b457824e4b38d0c932295.
```

I'm not really sure what I should do now.

**Comment by mkllnk** [comment] 2015-09-20 02:25
Okay, it looks like you have the same problem as #203 and #197. Thank you a lot for including the version numbers and the output. The release 1.0.2 doesn't support directories with the !-syntax yet. It treats them like files as you see in the output. But curl doesn't upload a whole directory.

It remains the question why the latest development version isn't working. In your case it's not displaying any of the files nor the directory, right?

Okay, I guess this command is failing:
```bash
find "wordpress/wp-content/themes/vgdw15/static/" -type f
```

It is the only usage of the `find` command in the code. Maybe that is not installed on your system or works differently. OSX?

**Comment by danieldiekmeier** [comment] 2015-09-21 09:11
Yes, OSX. This is an excerpt of `find "wordpress/wp-content/themes/vgdw15/static/" -type f`:

```
wordpress/wp-content/themes/vgdw15/static//css/style.css
wordpress/wp-content/themes/vgdw15/static//fonts/crimsontext-bold.eot
wordpress/wp-content/themes/vgdw15/static//fonts/crimsontext-bold.ttf
wordpress/wp-content/themes/vgdw15/static//fonts/crimsontext-bold.woff
wordpress/wp-content/themes/vgdw15/static//fonts/crimsontext-bold.woff2
[…]
```

I think the problem may be the double slashes?

**Comment by mkllnk** [comment] 2015-09-21 10:16
Interesting, thanks.

What if you remove the slash in `.git-ftp-include`?

    !wordpress/wp-content/themes/vgdw15/static

**Comment by danieldiekmeier** [comment] 2015-09-21 11:42
The files are still not included, sorry. :/

**Comment by mkllnk** [comment] 2015-09-23 10:13
I added some log messages to the file inclusion. If you download the latest `git-ftp` file and run it with `-v` again, you should see messages like 'Including ...' before 'Buffered for upload'.

Otherwise, you could run this as a test:
```sh
grep -v '^#.*$\|^\s*$' '.git-ftp-include' | tr -d '\r' | grep '^!' | sed 's/^!//' | while read TARGET; do
	echo "include: $TARGET"
done
```

Just to see if that code works as expected. It should output the lines starting with `!`.

Thanks a lot.

**Comment by mkllnk** [comment] 2015-10-04 21:13
Thanks to Travis CI providing Mac OS X build machines! I was able to reproduce this bug there and found the cause. OS X `grep -v -f <filter-file>` behaves differently to the GNU version if the filter file is empty. That one should be fixed in the current develop version. Thank you for the report again.

**Closed** 2015-10-04 21:13 UTC

**Comment by danieldiekmeier** [comment] 2015-10-06 18:20
Thank you for taking the time to look into this! <3

**Comment by Anahkiasen** [comment] 2015-10-21 14:37
Could we get a tag with this? Having the same issue

**Comment by mkllnk** [comment] 2015-10-24 07:56
@Anahkiasen Are you using 1.0.2? I wasn't aware that the bug was in that version as well. A backport of the fix is a bit more work. But probably I can do a 1.1.0 release candidate. Would that help?

**Comment by Anahkiasen** [comment] 2015-10-24 12:21
Well maybe it's a different bug and I didn't get the issue. I put `public/builds` into my `.git-ftp-include` and the files never get uploaded. Tried `!public/builds`, `public/builds/*` etc, none of them send any files. Running 1.0.2 at the moment

**Comment by mkllnk** [comment] 2015-10-24 22:35
@Anahkiasen The 1.0 release doesn't support including whole directories yet. You will find a new release candidate of version 1.1.
